THEME_NAME="rose-pine-dawn"
THEME_MODE="light"

BG="#faf4ed"
BG_ALT="#fffaf3"
SURFACE="#f2e9e1"
SURFACE_HOVER="#dfdad9"
FG="#575279"
FG_MUTED="#797593"
BORDER="#cecacd"
ACCENT="#907aa9"
ACCENT_2="#56949f"
DANGER="#b4637a"
WARNING="#ea9d34"
SUCCESS="#286983"

BLACK="#575279"
RED="#b4637a"
GREEN="#286983"
YELLOW="#ea9d34"
BLUE="#56949f"
MAGENTA="#907aa9"
CYAN="#d7827e"
WHITE="#cecacd"
BRIGHT_BLACK="#797593"
BRIGHT_CYAN="#56949f"
BRIGHT_WHITE="#575279"
