#################
### AUTOSTART ###
#################

# Autostart necessary processes (like notifications daemons, status bars, etc.)
# Or execute your favorite apps at launch like this:

exec-once = fcitx5 -d
# exec-once = nm-applet &
exec-once = qs -p ~/.config/quickshell --no-duplicate & hyprpaper & ~/.local/bin/hypr-idle-settings start & wl-paste --watch cliphist store
exec-once = hyprpm reload -n

#############################
### ENVIRONMENT VARIABLES ###
#############################
