THEME_NAME="dracula"
THEME_MODE="dark"

BG="#282a36"
BG_ALT="#21222c"
SURFACE="#343746"
SURFACE_HOVER="#44475a"
FG="#f8f8f2"
FG_MUTED="#bdc3d6"
BORDER="#6272a4"
ACCENT="#bd93f9"
ACCENT_2="#8be9fd"
DANGER="#ff5555"
WARNING="#f1fa8c"
SUCCESS="#50fa7b"

BLACK="#282a36"
RED="#ff5555"
GREEN="#50fa7b"
YELLOW="#f1fa8c"
BLUE="#8be9fd"
MAGENTA="#ff79c6"
CYAN="#8be9fd"
WHITE="#f8f8f2"
BRIGHT_BLACK="#6272a4"
BRIGHT_CYAN="#8be9fd"
BRIGHT_WHITE="#ffffff"
