#!/bin/sh
set -eu

# Keep packages that are useful in the Hyprland setup but were installed as KDE dependencies.
sudo pacman -D --asexplicit pipewire-pulse mpv noto-fonts-emoji

sudo pacman -Rns \
  akonadi-calendar \
  akonadi-calendar-tools \
  akonadi-import-wizard \
  akonadiconsole \
  akregator \
  angelfish \
  ark \
  aurorae \
  bluedevil \
  breeze \
  breeze-gtk \
  breeze-plymouth \
  calendarsupport \
  dolphin \
  dolphin-plugins \
  falkon \
  filelight \
  grantlee-editor \
  gwenview \
  incidenceeditor \
  kaddressbook \
  kate \
  kcalc \
  kclock \
  kde-cli-tools \
  kde-dev-scripts \
  kde-dev-utils \
  kde-gtk-config \
  kde-inotify-survey \
  kdebugsettings \
  kdeconnect \
  kdecoration \
  kdegraphics-thumbnailers \
  kdenetwork-filesharing \
  kdenlive \
  kdepim-addons \
  kdepim-runtime \
  kdeplasma-addons \
  kdesdk-kio \
  kdesdk-thumbnailers \
  kdevelop \
  kdevelop-php \
  kdevelop-python \
  kdialog \
  kglobalacceld \
  kinfocenter \
  kio-admin \
  kio-extras \
  kio-gdrive \
  kio-zeroconf \
  kirigami-gallery \
  knights \
  kmail \
  konqueror \
  konsole \
  kontact \
  korganizer \
  kscreen \
  kscreenlocker \
  kwallet-pam \
  kwalletmanager \
  kweather \
  kwin \
  kwin-x11 \
  libksieve \
  libplasma \
  mailcommon \
  mailimporter \
  mbox-importer \
  merkuro \
  messagelib \
  milou \
  okular \
  oxygen \
  partitionmanager \
  pim-data-exporter \
  pim-sieve-editor \
  pimcommon \
  plasma-activities \
  plasma-activities-stats \
  plasma-browser-integration \
  plasma-desktop \
  plasma-disks \
  plasma-firewall \
  plasma-integration \
  plasma-nm \
  plasma-pa \
  plasma-sdk \
  plasma-systemmonitor \
  plasma-thunderbolt \
  plasma-vault \
  plasma-welcome \
  plasma-workspace \
  plasma-workspace-wallpapers \
  plasma5support \
  plasmatube \
  powerdevil \
  print-manager \
  qqc2-breeze-style \
  spectacle \
  sweeper \
  systemsettings \
  wacomtablet \
  xdg-desktop-portal-kde \
  yakuake \
  zanshin
